import type { Metadata } from "next"
import { Gabarito } from "next/font/google"
import localFont from "next/font/local"

import { cn } from "@/lib/utils"
import Header from "@/components/layout/Header"
import { TailwindIndicator } from "@/components/TailwindIndicator"

import "./globals.css"

const gabarito = Gabarito({ subsets: ["latin"] })

const aeonik = localFont({
  src: "../../public/fonts/aeonik.woff2",
  display: "swap",
  variable: "--font-aeonik",
})

const untitled = localFont({
  src: [
    {
      path: "../../public/fonts/sans-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/sans-medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-untitled",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn(
            "font-aeonik selection:bg-theColor bg-[#1B1B1E] antialiased selection:text-white",
            aeonik.variable,
            untitled.variable
          )}
        >
          <div className="relative flex min-h-screen flex-col bg-zinc-950">
            <Header />
            <main className="flex-1">{children}</main>
            {/* <SiteFooter /> */}
          </div>
          <TailwindIndicator />
        </body>
      </html>
    </>
  )
}
